---
title: "Mini-Project 2"
author: "Leigh Tanji & Samantha Linder"
date: "October 31, 2017"
output: html_document
---


## Loading the data

This project is so interesting and relevant to my life!

I hope we can make this work

>>>>>>> 88b9ae9dda3e5db8b100c34ac26bccfcc4f30449
```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
tbl_df(house_elections)
```

#Democrat + Republican Incumbents
What percent democrat incumbents won their elections?
```{r}
parties <- c("D", "R")

incumbs<- function(party_arg) {
house_elections %>%
  filter(incumbent == "TRUE" &  party == party_arg) %>%
  summarise(winners = sum(ge_winner == "W"), 
            total_incumbents = n(),
            percent_incumb= winners *100/total_incumbents) 
}

lapply(parties, incumbs)
```

Checking the 'total_incumbs' numbers from 'incumbs'. Should be 169 and 224. 
```{r}
total_incumbs <- function(party_arg) {
  house_elections %>%
  filter(incumbent == "TRUE" & party == party_arg) %>%
  group_by(candidate_name) %>%
  select(candidate_name, incumbent, party)
}

lapply(parties, total_incumbs)
```

Checking the 'winners_incumb' numbers from 'incumbs'. Should be 152 and 199.
```{r}
winners_incumbs <- function(party_arg) {
  house_elections %>%
  filter(incumbent == "TRUE" &  party == party_arg & ge_winner == "W") %>%
  group_by(candidate_name) %>%
  select(candidate_name, incumbent, ge_winner, party)
}

lapply(parties, winners_incumbs)
```





























